services:
  journeyjoyapp_frontend:
    container_name: journeyjoy_frontend_c
    build: ./frontend
    image: journeyjoy_frontend:1
    ports: 
      - "5173:5173"
    networks:
      - journeyjoy_network
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

  journeyjoyapp_backend:
    container_name: journeyjoy_backend_c
    build: ./backend
    image: journeyjoy_backend:1
    ports:
      - "8080:8080"
    networks:
      - journeyjoy_network

  journeyjoy_db:
    container_name: journeyjoy_db_c
    image: mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INIT_DB_ROOT_USERNAME=root
      - MONGO_INIT_DB_ROOT_PASSWORD=root456
    volumes:
      - journeyjoy_mongo_data:/app/data
    networks:
      - journeyjoy_network

networks:
  journeyjoy_network: 

volumes:
  journeyjoy_mongo_data: